# Generated by Django 4.1.2 on 2022-10-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_remove_user_roomname_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapi.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapi.user'),
        ),
    ]
